language: julia
julia:
  - 0.6
notifications:
    email: true
script:
    - julia -e 'versioninfo(); Pkg.init(); Pkg.clone("https://github.com/saltpork/Stage.jl"); Pkg.clone("https://github.com/mit-nlp/Ollam.jl"); Pkg.clone(pwd())'
    - cd test; julia --color runtests.jl
